
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'WidgetComponentsChatBubbleComponentsBotChatBubble': typeof import("../components/widget-components/chat-bubble-components/bot-chat-bubble.vue")['default']
    'WidgetComponentsChatBubbleComponentsMovieList': typeof import("../components/widget-components/chat-bubble-components/movie-list.vue")['default']
    'WidgetComponentsChatBubbleComponentsRecommendList': typeof import("../components/widget-components/chat-bubble-components/recommend-list.vue")['default']
    'WidgetComponentsChatBubbleComponentsReviewModalsReviewModal': typeof import("../components/widget-components/chat-bubble-components/review-modals/review-modal.vue")['default']
    'WidgetComponentsChatBubbleComponentsUserChatBubble': typeof import("../components/widget-components/chat-bubble-components/user-chat-bubble.vue")['default']
    'WidgetComponentsChatInput': typeof import("../components/widget-components/chat-input.vue")['default']
    'WidgetComponentsChatScreen': typeof import("../components/widget-components/chat-screen.vue")['default']
    'WidgetComponentsChatSuggestion': typeof import("../components/widget-components/chat-suggestion.vue")['default']
    'WidgetComponentsHeader': typeof import("../components/widget-components/header.vue")['default']
    'Widget': typeof import("../components/widget.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtSnackbar': typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyWidgetComponentsChatBubbleComponentsBotChatBubble': typeof import("../components/widget-components/chat-bubble-components/bot-chat-bubble.vue")['default']
    'LazyWidgetComponentsChatBubbleComponentsMovieList': typeof import("../components/widget-components/chat-bubble-components/movie-list.vue")['default']
    'LazyWidgetComponentsChatBubbleComponentsRecommendList': typeof import("../components/widget-components/chat-bubble-components/recommend-list.vue")['default']
    'LazyWidgetComponentsChatBubbleComponentsReviewModalsReviewModal': typeof import("../components/widget-components/chat-bubble-components/review-modals/review-modal.vue")['default']
    'LazyWidgetComponentsChatBubbleComponentsUserChatBubble': typeof import("../components/widget-components/chat-bubble-components/user-chat-bubble.vue")['default']
    'LazyWidgetComponentsChatInput': typeof import("../components/widget-components/chat-input.vue")['default']
    'LazyWidgetComponentsChatScreen': typeof import("../components/widget-components/chat-screen.vue")['default']
    'LazyWidgetComponentsChatSuggestion': typeof import("../components/widget-components/chat-suggestion.vue")['default']
    'LazyWidgetComponentsHeader': typeof import("../components/widget-components/header.vue")['default']
    'LazyWidget': typeof import("../components/widget.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtSnackbar': typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const WidgetComponentsChatBubbleComponentsBotChatBubble: typeof import("../components/widget-components/chat-bubble-components/bot-chat-bubble.vue")['default']
export const WidgetComponentsChatBubbleComponentsMovieList: typeof import("../components/widget-components/chat-bubble-components/movie-list.vue")['default']
export const WidgetComponentsChatBubbleComponentsRecommendList: typeof import("../components/widget-components/chat-bubble-components/recommend-list.vue")['default']
export const WidgetComponentsChatBubbleComponentsReviewModalsReviewModal: typeof import("../components/widget-components/chat-bubble-components/review-modals/review-modal.vue")['default']
export const WidgetComponentsChatBubbleComponentsUserChatBubble: typeof import("../components/widget-components/chat-bubble-components/user-chat-bubble.vue")['default']
export const WidgetComponentsChatInput: typeof import("../components/widget-components/chat-input.vue")['default']
export const WidgetComponentsChatScreen: typeof import("../components/widget-components/chat-screen.vue")['default']
export const WidgetComponentsChatSuggestion: typeof import("../components/widget-components/chat-suggestion.vue")['default']
export const WidgetComponentsHeader: typeof import("../components/widget-components/header.vue")['default']
export const Widget: typeof import("../components/widget.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtSnackbar: typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyWidgetComponentsChatBubbleComponentsBotChatBubble: typeof import("../components/widget-components/chat-bubble-components/bot-chat-bubble.vue")['default']
export const LazyWidgetComponentsChatBubbleComponentsMovieList: typeof import("../components/widget-components/chat-bubble-components/movie-list.vue")['default']
export const LazyWidgetComponentsChatBubbleComponentsRecommendList: typeof import("../components/widget-components/chat-bubble-components/recommend-list.vue")['default']
export const LazyWidgetComponentsChatBubbleComponentsReviewModalsReviewModal: typeof import("../components/widget-components/chat-bubble-components/review-modals/review-modal.vue")['default']
export const LazyWidgetComponentsChatBubbleComponentsUserChatBubble: typeof import("../components/widget-components/chat-bubble-components/user-chat-bubble.vue")['default']
export const LazyWidgetComponentsChatInput: typeof import("../components/widget-components/chat-input.vue")['default']
export const LazyWidgetComponentsChatScreen: typeof import("../components/widget-components/chat-screen.vue")['default']
export const LazyWidgetComponentsChatSuggestion: typeof import("../components/widget-components/chat-suggestion.vue")['default']
export const LazyWidgetComponentsHeader: typeof import("../components/widget-components/header.vue")['default']
export const LazyWidget: typeof import("../components/widget.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtSnackbar: typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
