// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/14/2024, 1:53:01 PM
const configMerger = require("D:/chatbot-widget/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/chatbot-widget/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/plugins/**/*.{js,ts,mjs}","D:/chatbot-widget/composables/**/*.{js,ts,mjs}","D:/chatbot-widget/utils/**/*.{js,ts,mjs}","D:/chatbot-widget/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/chatbot-widget/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "D:/chatbot-widget/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
