// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/30/2024, 3:06:40 PM
const configMerger = require("D:/chat-widget-fpt-play/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/chat-widget-fpt-play/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/plugins/**/*.{js,ts,mjs}","D:/chat-widget-fpt-play/composables/**/*.{js,ts,mjs}","D:/chat-widget-fpt-play/utils/**/*.{js,ts,mjs}","D:/chat-widget-fpt-play/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/chat-widget-fpt-play/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "D:/chat-widget-fpt-play/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
